### ISSUE TITLE
Can't change the port in nbd-server

### ISSUE THREAD

**Issue by DonManley** [yoe/nbd#27] opened 2015-06-19 17:41 UTC
~ sudo nbd-server localhost:9000
    ~ sudo netstat -tlnp
    Active Internet connections (only servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
    tcp        0      0 0.0.0.0:10809           0.0.0.0:*               LISTEN      3350/nbd-server     

As you can see it still listens to the default port. The following prints the warning, but at least it listens to the right port:

    ~ sudo nbd-server localhost:9000 /dev/sdc
    ** (process:3121): WARNING **: Specifying an export on the command line is deprecated.

    ** (process:3121): WARNING **: Please use a configuration file instead.

Unfortunately, for some reason it also listens to a bunch of other ports as well:

    ~ sudo netstat -tlnp
    Active Internet connections (only servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
    tcp        0      0 0.0.0.0:55055           0.0.0.0:*               LISTEN      3122/nbd-server                
    tcp        0      0 0.0.0.0:10809           0.0.0.0:*               LISTEN      3122/nbd-server     
    tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      3122/nbd-server             
    tcp6       0      0 :::51489                :::*                    LISTEN      3122/nbd-server     
    tcp6       0      0 ::1:9000                :::*                    LISTEN      3122/nbd-server

The configuration was simple:

    [generic]
      user = nbd
      group = nbd
    [otherexport]
        exportname = /dev/sdc
        #port = 9000

Old school does not work:

    [generic]
      oldstyle=true
      user = nbd
      group = nbd
    [otherexport]
        exportname = /dev/sdc
        port = 9000

because it just exits:

    ~ sudo nbd-server
    ** Message: Since 3.10, the oldstyle protocol is no longer supported. Please migrate to the newstyle protocol.
    ** Message: Exiting.

Is it a bug or how can specify the port it should listen to? Why does it listen to a bunch of other ports as well? Of course, I can just block those ports at the firewall level, but this is still a peculiar behavior.

**Comment by yoe** [comment] 2015-06-21 07:53
The oldstyle (port-based) negotiation protocol has been removed in 3.10 and will not be coming back. It was only still provided for backwards compatibility, and was starting to cause problems.

It is true that there are still a few cases where nbd-server wants to use the oldstyle protocol to negotiate, but those are dead code paths. This is a bug, which will be fixed for 3.12 (so that it will move to using the newstyle negotiation protocol from those code paths, although the command line syntax may remain).

Since oldstyle is removed, it is no longer possible (or useful) to specify per-export port numbers. However, it is possible to vary the newstyle port number by specifying a port number in the [generic] section. If you do that, you can connect to it like so:

    nbd-client -N <name> <hostname> <port>

I'm not sure where the extraneous ports come from, and can't reproduce that. Which version are you using?

**Closed** 2015-11-08 10:43 UTC
